"""initial

Revision ID: 8ffdb49ed294
Revises: 
Create Date: 2024-04-14 21:27:33.251489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ffdb49ed294'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('skills')
    op.drop_index('ix_projects_end_date', table_name='projects')
    op.drop_index('ix_projects_start_date', table_name='projects')
    op.drop_table('projects')
    op.drop_table('worker_project')
    op.drop_table('worker_skill')
    op.drop_table('workers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=15), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('worker_skill',
    sa.Column('worker_id', sa.NUMERIC(), nullable=True),
    sa.Column('skill_id', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], )
    )
    op.create_table('worker_project',
    sa.Column('worker_id', sa.NUMERIC(), nullable=True),
    sa.Column('project_id', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], )
    )
    op.create_table('projects',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projects_start_date', 'projects', ['start_date'], unique=False)
    op.create_index('ix_projects_end_date', 'projects', ['end_date'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('worker_id', sa.NUMERIC(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
